// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWIcTrd2tIpZhwJMoFCqS6EbaaKzAhghQ',
    appId: '1:767263885139:web:56aea6985db84176c283a6',
    messagingSenderId: '767263885139',
    projectId: 'expense-tracker-1bdcf',
    authDomain: 'expense-tracker-1bdcf.firebaseapp.com',
    storageBucket: 'expense-tracker-1bdcf.appspot.com',
    measurementId: 'G-0VVZH34Y82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi4qbGgAJ4m4Nbv1KCN0DYLjUSGUNq7Dg',
    appId: '1:767263885139:android:93890ac5365fe584c283a6',
    messagingSenderId: '767263885139',
    projectId: 'expense-tracker-1bdcf',
    storageBucket: 'expense-tracker-1bdcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKTaZO1Ql3tkFlXxqdnCn0eihtNkmewLU',
    appId: '1:767263885139:ios:43e7a778c9e0c07ec283a6',
    messagingSenderId: '767263885139',
    projectId: 'expense-tracker-1bdcf',
    storageBucket: 'expense-tracker-1bdcf.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKTaZO1Ql3tkFlXxqdnCn0eihtNkmewLU',
    appId: '1:767263885139:ios:43e7a778c9e0c07ec283a6',
    messagingSenderId: '767263885139',
    projectId: 'expense-tracker-1bdcf',
    storageBucket: 'expense-tracker-1bdcf.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWIcTrd2tIpZhwJMoFCqS6EbaaKzAhghQ',
    appId: '1:767263885139:web:34cb97588f675171c283a6',
    messagingSenderId: '767263885139',
    projectId: 'expense-tracker-1bdcf',
    authDomain: 'expense-tracker-1bdcf.firebaseapp.com',
    storageBucket: 'expense-tracker-1bdcf.appspot.com',
    measurementId: 'G-WLKH9VCJYW',
  );
}
